// Writes the contract ABIs to web/src/lib/abis.ts so the web app stays in sync with the contracts.
import { readFileSync, writeFileSync } from "node:fs";

const names = ["AgentWallet", "AgentWalletFactory", "MilestoneEscrow", "MockUSDC"];
let out = "// Generated by contracts/scripts/export-abis.mjs. Do not edit.\n";
for (const name of names) {
  const artifact = JSON.parse(readFileSync(`artifacts/contracts/${name}.sol/${name}.json`, "utf8"));
  const id = name[0].toLowerCase() + name.slice(1);
  out += `\nexport const ${id}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync("../web/src/lib/abis.ts", out);
console.log("Wrote web/src/lib/abis.ts");
